//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::auth::Entity as Auth;
pub use super::client::Entity as Client;
pub use super::salt::Entity as Salt;
pub use super::web_auth::Entity as WebAuth;
