//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;
use sea_orm::FromQueryResult;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, serde::Serialize, serde::Deserialize)]
#[sea_orm(table_name = "web_auth")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub username: String,
    #[sea_orm(column_type = "Text")]
    pub hashed_password: String,
    #[sea_orm(column_type = "Text")]
    pub salt: String,
}

#[derive(DerivePartialModel, FromQueryResult, serde::Serialize, serde::Deserialize)]
#[sea_orm(entity = "Entity")]
pub struct PartialModel {
    pub username: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
