//
// Created by Jhean Lee on 2025/1/24.
//

#ifndef AQUEDUCT_CONSOLE_HPP
  #define AQUEDUCT_CONSOLE_HPP
  #include <string>

  enum Level {
    CRITICAL,
    ERROR,
    WARNING,
    NOTICE,
    INFO,
    DEBUG,
  };

  enum Code {
    //  api
    API_SOCK_CREATE_FAILED,
    API_SOCK_BIND_FAILED,
    API_SOCK_LISTEN_FAILED,
    API_SOCK_ACCEPT_FAILED,
    API_SOCK_POLL_ERR,

    API_LISTEN_STARTED,
    API_SERVICE_ENDED,
    API_CLIENT_CONNECTION_ACCEPTED,
    API_CONNECTION_CLOSED,
    API_HEARTBEAT_TIMEOUT,

    API_START_PROCESS_FAILED,
    API_PROCESS_STARTED,
    API_PROCESS_ENDED,

    //  connection
    SOCK_CREATE_FAILED,
    SOCK_BIND_FAILED,
    SOCK_LISTEN_FAILED,
    SOCK_ACCEPT_FAILED,
    SOCK_SETSOCKOPT_FAILED,
    SOCK_POLL_ERR,

    //  ssl (connection)
    SSL_CREATE_CONTEXT_FAILED,
    SSL_ACCEPT_FAILED,
    SSL_LOAD_CERT_KEY_FAILED,

    //  ssl (cert, key)
    SSL_INIT_FAILED,
    SSL_BIO_FAILED,
    SSL_RSA_FAILED,
    SSL_KEY_WRITE_FAILED,
    SSL_CERT_WRITE_FAILED,
    SSL_CERT_SIGN_FAILED,

    //  database
    SQLITE_OPEN_FAILED,
    SQLITE_CREATE_TABLE_FAILED,
    SQLITE_PREPARE_FAILED,
    SQLITE_BIND_PARAMETER_FAILED,
    SQLITE_STEP_FAILED,
    SQLITE_RETRIEVE_FAILED,
    SQLITE_CLOSING,
    SQLITE_CLOSE_SUCCESS,
    SQLITE_CLOSE_FAILED,

    SHA256_INIT_CONTEXT_FAILED,
    SHA256_SET_CONTEXT_FAILED,
    SHA256_UPDATE_CONTEXT_FAILED,
    SHA256_FINALISE_CONTEXT_FAILED,
    RAND_FAILED,

    INVALID_DB,

    //  token
    GENERATED_TOKEN,
    REMOVED_TOKEN,

    //  option
    OPTION_UNKNOWN,
    OPTION_KEY_NOT_SET,
    OPTION_CERT_NOT_SET,
    PORT_INVALID_CHARACTER,
    PORT_INVALID_RANGE,
    PORT_WELL_KNOWN,
    PORT_INVALID_LIMIT,
    PORT_MAY_EXCEED,

    INFO_SSL_KEY_PATH,
    INFO_SSL_CERT_PATH,
    INFO_JWT_PUBKEY_PATH,
    INFO_JWT_PRIVKEY_PATH,
    INFO_DB_PATH,
    INFO_HOST,

    //  message
    MESSAGE_SEND_FAILED,
    MESSAGE_LOAD_FAILED,
    MESSAGE_DUMP_FAILED,
    BUFFER_SEND_ERROR_TO_CLIENT,
    BUFFER_SEND_ERROR_TO_EXTERNAL_USER,

    //  tunnel
    CONNECTION_LISTEN_STARTED,
    TUNNEL_SERVICE_ENDED,
    CLIENT_CONNECTION_ACCEPTED,
    EXTERNAL_CONNECTION_ACCEPTED,
    CONNECTION_CLOSED,
    CONNECTION_CLOSED_BY_CLIENT,
    CONNECTION_CLOSED_BY_EXTERNAL_USER,
    HEARTBEAT_TIMEOUT,
    AUTHENTICATION_FAILED,
    AUTHENTICATION_SUCCESS,
    PROXY_PORT_NEW,
    PROXYING_STARTED,
    PROXYING_ENDED,
    NO_PORT_AVAILABLE,

    //  file
    CREATE_DIR_FAILED,

    //  signal
    SIGNAL,

    //  debug
    DEBUG_MSG,
  };

  void console(Level level, Code code, const char *detail, const std::string &function);
#endif //AQUEDUCT_CONSOLE_HPP
